name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: 1.26

    - name: golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2
        golangci-lint run --enable-only=govet,unused

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -failfast -timeout 60s -v ./...
